package com.simpleSQL.model;

public enum ProjectEvent {
	ADDED_COMPONENT,
	REMOVED_COMPONENT,
	PASTED_COMPONENT,
	COPIED_COMPONENT,
	RENAMED_COMPONENT,
	ADDED_CONNECTION,
	REMOVED_CONNECTION, ADDED_ENTITY, ADDED_RELATION, ADDED_ATTRIBUTE,
}
