package com.simpleSQL.models;

public enum Property {
	AUTO_SAVE_INTERVAL, DEFAULT_DATABASE_CHARSET, SHOW_LINE_NUMBERS, DEFAULT_SQL_MODE, CONFIRM_ON_CLOSE, THEME,
	FONT_SIZE, SYNTAX_HIGHLIGHTING, UI_SCALING, SHOW_GRID_LINES, TAB_WIDTH, AUTO_INDENTATION, CODE_COMPLETION,
	QUERY_HISTORY_SIZE, ERROR_HIGHLIGHTING, DEFAULT_HOST, CONNECTION_TIMEOUT, SSL_CONNECTION, DEFAULT_PORT,
	RECONNECT_ON_FAILURE, PROJECT_PATH, EER_DIAGRAM_AUTO_SAVE, MAX_UNDO_STEPS, TABLE_NAMING_CONVENTION,
	DEFAULT_DATA_TYPES, AUTO_SAVE, EDITOR_FONT_SIZE, SHOW_SYNTAX_ERROR, DEFAULT_USER, DEFAULT_PASSWORD,
	RECONNECT_ON_FAILURE_TRIES, DEFAULT_SAVE_PATH
}
